In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [4]:
# data loading
df = pd.read_csv("../data/raw/cleaned_data.csv")
df.head()

   Age     Sex  Job Housing  ... Credit amount Duration              Purpose  Risk
0   67    male    2     own  ...          1169        6             radio/TV  good
1   22  female    2     own  ...          5951       48             radio/TV   bad
2   49    male    1     own  ...          2096       12            education  good
3   45    male    2    free  ...          7882       42  furniture/equipment  good
4   53    male    2    free  ...          4870       24                  car   bad

[5 rows x 10 columns]

In [5]:
# One hot encoding of Sex, Housing, Purpose columns

df = pd.get_dummies(
    df,
    columns = ['Sex', 'Housing', 'Purpose'],
    drop_first = True,
    dtype = int
)

df.head()

   Age  Job  ... Purpose_repairs Purpose_vacation/others
0   67    2  ...               0                       0
1   22    2  ...               0                       0
2   49    1  ...               0                       0
3   45    2  ...               0                       0
4   53    2  ...               0                       0

[5 rows x 17 columns]

In [6]:
# Savings account mapping

saving_map = {
    "No Account": 0,
    "little": 1,
    "moderate": 2,
    "quite rich": 3,
    "rich": 4
}

df["Saving accounts"] = df["Saving accounts"].map(saving_map)

In [7]:
# checking account mapping

checking_map = {
    "No Account" : 0,
    "little" : 1,
    "moderate" : 3,
    "rich" : 4
}

df['Checking account'] = df["Checking account"].map(checking_map)

In [8]:
# encoding the target variable (Risk)

df['Risk'] = df['Risk'].map({
    "bad" : 1,
    "good" : 0
})

In [9]:
df.head(10)

   Age  Job  ...  Purpose_repairs  Purpose_vacation/others
0   67    2  ...                0                        0
1   22    2  ...                0                        0
2   49    1  ...                0                        0
3   45    2  ...                0                        0
4   53    2  ...                0                        0
5   35    1  ...                0                        0
6   53    2  ...                0                        0
7   35    3  ...                0                        0
8   61    1  ...                0                        0
9   28    3  ...                0                        0

[10 rows x 17 columns]

In [10]:
# splitting the train and test data
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    random_state= 42,
    test_size= 0.2,
    stratify= df['Risk']
)

In [12]:
# saving the test and train datasets

train_df.to_csv("../data/processed/train.csv", index= False)
test_df.to_csv("../data/processed/test.csv", index= False)